### ISSUE TITLE
CPP_EQUAL: equality issue

### ISSUE THREAD

**Issue by nihilscire** [alpha123/cpplib#1]
First of all, you've done good job with this preprocessor metaprogramming project.
I am actually using it in one of my C projects right now, and it comes very useful until the equality operator pops up.
Let's take a look at the following snippet
```
int main(int argc, char* argv[]){
    #if N == 100
    foo();
    #endif
    CPP_EQUAL(N,100)
    return 0;
}
```

I run the preprocessor as `gcc -E -DN=100 foo.c` and this is the result:
```
int main(int argc, char* argv[]){
    foo();
    0
    return 0;
}
```

Instead with `gcc -E -DN=150 foo.c`:
```
int main(int argc, char* argv[]){

    0
    return 0;
}
```

So it seems that CPP_EQUAL returns always zero. Am I missing something?

Thanks

**Comment by alpha123** [comment]
Ah, right, the way that works is a little funny. You have to define a macro `COMPARE_token(x) x` for every token you want to test for equality. This is because the C preprocessor gives us nothing except pattern matching, so the only way to check if two tokens are equal is to attempt to match them.

This works as expected:

```c
#define COMPARE_100(x) x
int main(int argc, char* argv[]){
    #if N == 100
    foo();
    #endif
    CPP_EQUAL(N,100)
    return 0;
}
```

I could add some predefined `COMPARE_` macros for numbers.

**Comment by nihilscire** [comment]
Oh I see! That's cumbersome, and it isn't scalable, too bad. 
Of course it's not your fault, thanks a lot for the help!
